"""initial

Revision ID: 2d250a5cdd67
Revises: 
Create Date: 2026-05-15 18:03:49.726566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d250a5cdd67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_mensais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mes_referencia', sa.CHAR(length=7), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('meta_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('recompensa_valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_bonus_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes_referencia', name='uq_bonus_mes_referencia')
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidade', sa.Enum('kg', 'un', name='enum_material_unidade'), nullable=False),
    sa.Column('pontos_por_unidade', sa.Integer(), nullable=False),
    sa.Column('valor_por_unidade', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_material_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_materiais_slug')
    )
    op.create_table('parceiros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('logo_emoji', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_parceiro_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_parceiros_nome')
    )
    op.create_table('pontos_coleta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.CHAR(length=2), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('distancia_km', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('abre_as', sa.Time(), nullable=True),
    sa.Column('fecha_as', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_ponto_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_pontos_coleta_slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.CHAR(length=2), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'operator', 'admin', name='enum_user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='enum_user_status'), nullable=False),
    sa.Column('saldo', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf', name='uq_usuarios_cpf'),
    sa.UniqueConstraint('email', name='uq_usuarios_email')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=False),
    sa.Column('janela_inicio', sa.Time(), nullable=False),
    sa.Column('janela_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'checked_in', 'completed', 'cancelled', 'missed', name='enum_agendamento_status'), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos_coleta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficios_parceiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('discount', 'credit', 'cashback', 'bill_payment', name='enum_beneficio_tipo'), nullable=False),
    sa.Column('custo_voucher', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('limite_periodo', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_beneficio_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parceiro_id', 'titulo', name='uq_beneficio_parceiro_titulo')
    )
    op.create_table('missoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('material_weight', 'material_count', 'monthly_goal', name='enum_missao_tipo'), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('meta_quantidade', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('recompensa_tipo', sa.Enum('voucher', 'xp', name='enum_missao_recompensa_tipo'), nullable=False),
    sa.Column('recompensa_valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('inicio_em', sa.Date(), nullable=False),
    sa.Column('fim_em', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_missao_status'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_missoes_slug')
    )
    op.create_table('operadores_ponto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_operador_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos_coleta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'ponto_id', name='uq_operador_ponto')
    )
    op.create_table('ponto_materiais',
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enum_ponto_material_status'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos_coleta.id'], ),
    sa.PrimaryKeyConstraint('ponto_id', 'material_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('tickets_suporte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('assunto', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='enum_ticket_status'), nullable=False),
    sa.Column('prioridade', sa.Enum('low', 'medium', 'high', name='enum_ticket_prioridade'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes_carteira',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('credit', 'debit', 'bonus', 'reversal', 'adjustment', name='enum_transacao_tipo'), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('saldo_resultante', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending_confirmation', 'confirmed', 'rejected', 'cancelled', name='enum_entrega_status'), nullable=False),
    sa.Column('observacoes_usuario', sa.String(length=255), nullable=True),
    sa.Column('observacoes_operador', sa.String(length=255), nullable=True),
    sa.Column('confirmado_por', sa.Integer(), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['confirmado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos_coleta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolo', name='uq_entregas_protocolo')
    )
    op.create_table('interacoes_suporte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_suporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missoes_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('missao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('progresso_atual', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'expired', name='enum_missao_usuario_status'), nullable=False),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('recompensa_creditada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['missao_id'], ['missoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('missao_id', 'usuario_id', name='uq_missao_usuario')
    )
    op.create_table('resgates_voucher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('beneficio_id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('valor_debitado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('codigo_resgate', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('generated', 'used', 'expired', 'cancelled', name='enum_resgate_status'), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('utilizado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficio_id'], ['beneficios_parceiro.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_resgate', name='uq_resgates_codigo')
    )
    op.create_table('entrega_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unidade', sa.Enum('kg', 'un', name='enum_entrega_item_unidade'), nullable=False),
    sa.Column('pontos_gerados', sa.Integer(), nullable=False),
    sa.Column('valor_creditado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrega_itens')
    op.drop_table('resgates_voucher')
    op.drop_table('missoes_usuario')
    op.drop_table('interacoes_suporte')
    op.drop_table('entregas')
    op.drop_table('transacoes_carteira')
    op.drop_table('tickets_suporte')
    op.drop_table('refresh_tokens')
    op.drop_table('ponto_materiais')
    op.drop_table('operadores_ponto')
    op.drop_table('missoes')
    op.drop_table('beneficios_parceiro')
    op.drop_table('agendamentos')
    op.drop_table('usuarios')
    op.drop_table('pontos_coleta')
    op.drop_table('parceiros')
    op.drop_table('materiais')
    op.drop_table('bonus_mensais')
    # ### end Alembic commands ###
